### ISSUE TITLE
Croaks with "TypeError: Discourse._registerPluginCode is not a function"

### ISSUE THREAD

**Issue by amotl** [discourse/discourse-brand-header#1]
Dear @vinothkannans and @hnb-ku,

first things first: Thanks for conceiving and maintaining Discourse and its wonderful ecosystem of addon components.

We are having a `TypeError: Discourse._registerPluginCode is not a function` with this theme component. It is reproducible happening on the `/u/activate-account` page when this plugin is active with the currently selected theme.

It looks like the main Discourse instance is not yet available when being called by the brand header theme component on the account activation page. This smells like a timing issue re. resource initialization order.

We provided more details on meta at [TypeError: Discourse._registerPluginCode is not a function](https://meta.discourse.org/t/typeerror-discourse-registerplugincode-is-not-a-function/88572/2).

Thanks in advance for having a look and keep up the spirit!

Cheers,
Andreas.

**Comment by vinothkannans** [comment]
This is fixed as per commit https://github.com/discourse/discourse/commit/59e5af466bdcdccc5aefc167061fe1c9276e624c. Thanks @amotl for your report and help.
